name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    
jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: 17
         distribution: 'adopt'
      - name: Maven Verify  
        run: mvn clean verify
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
         service-id: ${{ secrets.RENDER_ID }} 
         api-key: ${{ secrets.RENDER_API_KEY }}
