name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
 build:
  name: Deploy
  runs-on: ubuntu-18.04
  #needs: run_test
  steps:
    - run: echo "Starting build package"
    - uses: actions/checkout@v3
    - name: Render Deploy Action
    - uses: johnbeynon/render-deploy-action@v0.0.8
    - with:
       service-id: ${{ secrets.RENDER_ID }} 
       api-key: ${{ secrets.RENDER_API_KEY }}
